/** Local route paths mirroring Wix Bookings content segments. */
export const paths = {
  root: "/bookings",
  availability: "/bookings/availability",
  defaultHours: "/bookings/availability/default-hours",
  calendar: "/wix-calendar",
  bookingList: "/bookings/bookings/bookings-list",
  analytics: "/bookings/overviews/bookings",
  services: "/bookings/services",
  serviceTemplates: "/bookings/services/templates-catalog",
  serviceFormNew: "/bookings/services/form",
  serviceFormEdit: (id: string) => `/bookings/services/form/${id}`,
  integrations: "/bookings/integrations",
  shareableLinks: "/bookings/dashboard",
  staff: "/bookings/staff",
  staffEditNew: "/bookings/staff/edit",
  staffEdit: (id: string) => `/bookings/staff/edit/${id}`,
  settings: "/bookings/settings",
  addons: "/bookings/addons/addons",
  resources: "/wix-calendar/resource-management/index",
  remindersYouSend: "/bookings/settings/reminders/you-send/whatsapp",
  remindersYouGet: "/bookings/settings/reminders/you-get",
  bookflow: "/bookings/settings/bookflow-settings",
  formsManager: "/bookings/settings/forms-manager",
  policies: "/bookings/settings/policies",
} as const;
