import React from "react";
import { Filter, MailPlus, Search, Send } from "lucide-react";
import { DeveloperPageHeader, DeveloperToolsPage, DeveloperUnavailable, ml } from "./AdminDeveloperToolsShared.jsx";

export default function AdminTriggeredEmailsPage({ activePage, company, language = "en", onNavigate, ...layout }) {
  return <DeveloperToolsPage activePage={activePage} company={company} language={language} onNavigate={onNavigate} {...layout}>{(showUnavailable) => <>
    <DeveloperPageHeader actions={<button className="developer-tools-primary-button" onClick={showUnavailable} type="button"><MailPlus size={17} />{ml(language, "New Campaign", "حملة جديدة")}</button>} description={ml(language, "Prepare automated tenant communications when a verified email service is available.", "جهّز اتصالات المستأجر الآلية عند توفر خدمة بريد إلكتروني موثقة.")} language={language} onNavigate={onNavigate} title={ml(language, "Triggered Emails", "رسائل البريد المشغلة")} />
    <section className="developer-sender-banner"><span className="developer-sender-icon"><Send size={28} /></span><div><h2>{ml(language, "Add a sender", "إضافة مرسل")}</h2><p>{ml(language, "A verified sender is required before triggered email can be configured.", "يلزم مرسل موثق قبل إعداد البريد الإلكتروني المشغّل.")}</p></div><button className="developer-tools-secondary-button" onClick={showUnavailable} type="button">{ml(language, "Add Sender", "إضافة مرسل")}</button></section>
    <section className="developer-campaign-card"><div className="developer-campaign-toolbar"><div><h2>{ml(language, "Campaigns", "الحملات")}</h2><span>{ml(language, "No connected email service", "لا توجد خدمة بريد متصلة")}</span></div><div><button aria-label={ml(language, "Filter campaigns", "تصفية الحملات")} className="developer-tools-icon-button" disabled type="button"><Filter size={18} /></button><label className="developer-tools-search"><Search size={18} /><input disabled placeholder={ml(language, "Search campaigns", "البحث في الحملات")} /></label></div></div><div className="developer-campaign-stage"><DeveloperUnavailable icon={MailPlus} title={ml(language, "Set up triggered emails", "إعداد رسائل البريد المشغلة")} description={ml(language, "No verified tenant email-campaign service is connected. Campaigns, senders, recipients, and delivery history cannot be shown.", "لا توجد خدمة حملات بريد موثقة للمستأجر متصلة. لا يمكن عرض الحملات أو المرسلين أو المستلمين أو سجل التسليم.")} /><div className="developer-tools-empty-actions"><button className="developer-tools-primary-button" onClick={showUnavailable} type="button">{ml(language, "Get Started", "ابدأ")}</button><button className="developer-tools-text-button" onClick={showUnavailable} type="button">{ml(language, "Learn More", "معرفة المزيد")}</button></div></div></section>
  </>}</DeveloperToolsPage>;
}
